/**
 * Reference CV fixture derived from templates-layout PDFs.
 * Used for visual QA and tests only — never hard-coded into renderers.
 */
import type { CvDocument } from "@/features/cv-editor/types";
import { normalizePersonalInfo } from "@/lib/cvs/personal-info";

export const kennedySitholeReferenceFixture: CvDocument = {
  id: "ref-kennedy-sithole",
  title: "Software Engineer",
  templateId: "modern",
  templateSlug: "tpl_default",
  rendererKey: "tpl_default",
  updatedAt: "2026-08-14T00:00:00.000Z",
  personal: normalizePersonalInfo({
    fullName: "Kennedy Sithole",
    title: "Software Engineer",
    useAsHeadline: true,
    email: "kevykenny29@gmail.com",
    phone: "+263782186683",
    address: "40 Twickenham Dr, Mount Pleasant",
    postCode: "",
    city: "Harare",
    location: "Harare, Zimbabwe",
    driversLicense: "BE (Class 4)",
    linkedin: "linkedin.com/in/kennedysithole15",
    portfolio: "kennedy-sithole-portfolio.vercel.app",
    fieldVisibility: {
      linkedin: true,
      website: true,
      driversLicense: true,
    },
  }),
  summary:
    "Dedicated Software Engineer with over 2 years of professional experience designing and developing scalable web and cross-platform mobile applications. Skilled in React, Next.js, Node.js, Express, PostgreSQL, MongoDB, and Supabase, with experience delivering AI-powered solutions and collaborating in Agile development teams. A first-class honors computer science graduate committed to building high-quality, user-focused software and continuously expanding technical expertise.",
  experience: [
    {
      id: "exp-1",
      experienceType: "internship",
      company: "Home Snappers LLC",
      department: "",
      role: "Software Developer Intern",
      location: "Texas",
      dateMode: "range",
      startMonth: "09",
      startYear: "2023",
      endMonth: "06",
      endYear: "2024",
      duration: "",
      current: false,
      responsibilities: [
        "Actively participated in application development using JavaScript and modern frameworks.",
        "Developed front-end solutions using Next.js and Ionic for cross-platform mobile applications.",
        "Implemented back-end data management with Supabase and PostgreSQL database integration.",
      ],
      skillsGained: [],
      achievements: [],
      supervisor: { name: "", position: "", email: "", phone: "" },
      includeSupervisorOnExport: false,
    },
    {
      id: "exp-2",
      experienceType: "part-time",
      company: "Home Snappers LLC",
      position: "Part-Time Developer",
      location: "Texas",
      startMonth: "09",
      startYear: "2024",
      endMonth: "06",
      endYear: "2025",
      current: false,
      responsibilities: [
        "Developed full-stack applications using ReactJS, NextJS, Ionic, Node.js, and Express.",
        "Integrated databases using Supabase with PostgreSQL and MongoDB.",
        "Implemented responsive UI components and styling using Tailwind CSS.",
      ],
      skillsGained: [],
      achievements: [],
    },
    {
      id: "exp-3",
      experienceType: "full-time",
      company: "Zimotely LLC",
      position: "Software Engineer I",
      location: "Remote",
      startMonth: "06",
      startYear: "2025",
      endMonth: "",
      endYear: "",
      current: true,
      responsibilities: [
        "Develop and maintain full-stack features across a Turborepo monorepo.",
        "Design and implement REST APIs with Node.js and Fastify.",
        "Integrate MongoDB with Mongoose for schema design and backend persistence.",
      ],
      skillsGained: [],
      achievements: [],
    },
  ],
  education: [
    {
      id: "edu-1",
      qualificationType: "honours",
      institution: "University Of Zimbabwe",
      city: "Harare",
      qualification: "BSc (Hons) in Computer Science",
      field: "Computer Science",
      startMonth: "08",
      startYear: "2021",
      endMonth: "08",
      endYear: "2025",
      current: false,
      startDate: "2021-08-01",
      endDate: "2025-08-01",
      grade: "1st Class",
      achievements:
        "First Class Degree (Awarded with University Book Prize)",
      description: "",
    },
  ],
  skills: [
    { id: "s1", name: "JavaScript (ES6+)", category: "technical", level: null },
    { id: "s2", name: "HTML5 / CSS3 / Sass", category: "technical", level: null },
    { id: "s3", name: "TypeScript", category: "technical", level: null },
    { id: "s4", name: "React", category: "frameworks", level: null },
    { id: "s5", name: "Next.js", category: "frameworks", level: null },
    { id: "s6", name: "Node.js", category: "frameworks", level: null },
    { id: "s7", name: "Express.js", category: "frameworks", level: null },
    { id: "s8", name: "Ionic", category: "frameworks", level: null },
    { id: "s9", name: "PostgreSQL", category: "tools", level: null },
    { id: "s10", name: "MongoDB", category: "tools", level: null },
    { id: "s11", name: "Supabase", category: "tools", level: null },
    { id: "s12", name: "AWS S3", category: "tools", level: null },
    { id: "s13", name: "Vercel", category: "tools", level: null },
    { id: "s14", name: "GitHub", category: "tools", level: null },
    { id: "s15", name: "Heroku", category: "tools", level: null },
    { id: "s16", name: "Jira", category: "tools", level: null },
    {
      id: "s18",
      name: "Willingness to learn new skills",
      category: "soft",
      level: null,
    },
    {
      id: "s19",
      name: "Outstanding written and oral communication",
      category: "soft",
      level: null,
    },
    {
      id: "s20",
      name: "Exceptional interpersonal abilities",
      category: "soft",
      level: null,
    },
    {
      id: "s21",
      name: "Keen observational and listening skills",
      category: "soft",
      level: null,
    },
    {
      id: "s22",
      name: "Dynamic approach to teamwork",
      category: "soft",
      level: null,
    },
  ],
  projects: [
    {
      id: "p1",
      name: "Sell-Cattle",
      description:
        "AI-Powered Digital Platform for Direct meat sales and Farm Optimization (Thesis: June 2025)",
      technologies: [],
      link: "",
    },
    {
      id: "p2",
      name: "TillMate",
      description: "Offline-first Point-of-Sale mobile application",
      technologies: [],
      link: "",
    },
    {
      id: "p3",
      name: "SpeakFlow AI",
      description: "AI-powered Language and confidence Learning mobile application",
      technologies: [],
      link: "",
    },
  ],
  certifications: [
    {
      id: "c1",
      name: "JavaScript Essentials 1",
      provider: "Cisco",
      date: "2023-09",
      credentialUrl: "",
    },
    {
      id: "c2",
      name: "Pythons Essentials 1",
      provider: "Cisco",
      date: "2023-10",
      credentialUrl: "",
    },
  ],
  languages: [],
  achievements: [
    {
      id: "a1",
      title: "",
      description:
        "Awarded a degree with first class and a University of Zimbabwe book prize for exceptional engagement and consistent performance.",
    },
  ],
  references: [
    {
      id: "r1",
      name: "Mr. Hwande",
      relationship: "Home Snappers LLC, Texas",
      contact: "+1 (314) 541-3066, noel@homesnappers.com",
    },
    {
      id: "r2",
      name: "Mr. Rupere",
      relationship: "University of Zimbabwe, Harare",
      contact: "+263-4-333677, +263 772 416 888",
    },
    {
      id: "r3",
      name: "Mr. Munyaradzi",
      relationship: "University of Zimbabwe, Harare",
      contact: "+263 772 390 828",
    },
  ],
  sections: [
    { id: "sec-p", type: "personal", label: "Personal details", visible: true, completion: 0 },
    {
      id: "sec-s",
      type: "summary",
      label: "Professional Summary",
      visible: true,
      completion: 0,
    },
    { id: "sec-e", type: "experience", label: "Employment", visible: true, completion: 0 },
    { id: "sec-ed", type: "education", label: "Education", visible: true, completion: 0 },
    { id: "sec-sk", type: "skills", label: "Skills", visible: true, completion: 0 },
    { id: "sec-pj", type: "projects", label: "Projects", visible: true, completion: 0 },
    {
      id: "sec-ce",
      type: "certifications",
      label: "Certificates",
      visible: true,
      completion: 0,
    },
    { id: "sec-a", type: "achievements", label: "Achievements", visible: true, completion: 0 },
    { id: "sec-r", type: "references", label: "References", visible: true, completion: 0 },
  ],
};
